"""empty message

Revision ID: 0adf23b74c0d
Revises: 8d4853a0733d
Create Date: 2019-05-28 22:41:01.845978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adf23b74c0d'
down_revision = '8d4853a0733d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('edit_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'edit_type')
    # ### end Alembic commands ###
