"""empty message

Revision ID: 240062affe0c
Revises: f2d6c2615ef5
Create Date: 2019-02-08 09:13:00.602333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240062affe0c'
down_revision = 'f2d6c2615ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'view_count')
    # ### end Alembic commands ###
