"""empty message

Revision ID: 32a79bb7db1a
Revises: ac50a5d7c8ba
Create Date: 2019-01-14 21:33:00.866123

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


NOTE_TYPES = [
    ('database', 'Database'),
    ('web','Web'),
    ('docker', 'Docker'),
    ('security', 'Security')
]

# revision identifiers, used by Alembic.
revision = '32a79bb7db1a'
down_revision = 'ac50a5d7c8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('note_type', sqlalchemy_utils.types.choice.ChoiceType(NOTE_TYPES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'note_type')
    # ### end Alembic commands ###
