"""empty message

Revision ID: 352e97ad0669
Revises: 
Create Date: 2019-01-20 22:26:02.361945

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '352e97ad0669'
down_revision = None
branch_labels = None
depends_on = None
NOTE_TYPES = [
    (1, 'database'),
    (2, 'web'),
    (3, 'docker'),
    (4, 'security')
]

USER_ROLES = [
    (0, 'vip'),
    (1, 'Common'),
]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=100), nullable=True),
    sa.Column('user_email', sa.String(length=512), nullable=True),
    sa.Column('user_role', sqlalchemy_utils.types.choice.ChoiceType(USER_ROLES, impl=sa.Integer()), nullable=True, default=1),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('note_type', sqlalchemy_utils.types.choice.ChoiceType(NOTE_TYPES, impl=sa.Integer()), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('user')
    # ### end Alembic commands ###
