"""empty message

Revision ID: 8d4853a0733d
Revises: 
Create Date: 2019-05-28 22:37:02.837754

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8d4853a0733d'
down_revision = None
branch_labels = None
depends_on = None

NOTE_TYPES = [
    (1, 'database'),
    (2, 'web'),
    (3, 'docker'),
    (4, 'security'),
    (5, 'notice')
]

USER_ROLES = [
    (1, 'Admin'),
    (2, 'Common'),
    (3, 'Vip')
]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=100), nullable=True),
    sa.Column('user_email', sa.String(length=512), nullable=True),
    sa.Column('user_role', sqlalchemy_utils.types.choice.ChoiceType(USER_ROLES, impl=sa.Integer()), nullable=True),
    sa.Column('is_auditing', sa.Boolean(), nullable=True),
    sa.Column('user_avatar', sa.String(length=512), nullable=True),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('note_type', sqlalchemy_utils.types.choice.ChoiceType(NOTE_TYPES, impl=sa.Integer()), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prase_count', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('noteId', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['noteId'], ['note.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('upload')
    op.drop_table('note')
    op.drop_table('user')
    # ### end Alembic commands ###
