"""empty message

Revision ID: 962416b0fbae
Revises: 8a6046df876d
Create Date: 2019-02-17 19:14:23.699923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962416b0fbae'
down_revision = '8a6046df876d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_description')
    # ### end Alembic commands ###
