"""empty message

Revision ID: 99580212e018
Revises: 32a79bb7db1a
Create Date: 2019-01-20 21:15:35.564419

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '99580212e018'
down_revision = '32a79bb7db1a'
branch_labels = None
depends_on = None

USER_ROLES = [
    ('vip', 'Vip'),
    ('common', 'Common'),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role', sqlalchemy_utils.types.choice.ChoiceType(USER_ROLES), nullable=True, default='vip'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_role')
    # ### end Alembic commands ###
