"""empty message

Revision ID: b0f1360bbb21
Revises: 4313a24e6888
Create Date: 2019-02-01 14:07:46.570825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f1360bbb21'
down_revision = '4313a24e6888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('raw_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'raw_content')
    # ### end Alembic commands ###
