"""empty message

Revision ID: b7dce1cf6051
Revises: 0adf23b74c0d
Create Date: 2019-05-28 23:14:12.248006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dce1cf6051'
down_revision = '0adf23b74c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('edit_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'edit_type')
    # ### end Alembic commands ###
