"""empty message

Revision ID: f2d6c2615ef5
Revises: a440dc2f16a8
Create Date: 2019-02-06 19:01:24.821149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d6c2615ef5'
down_revision = 'a440dc2f16a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'update_time')
    # ### end Alembic commands ###
